site_name: PR-Insight (formerly known as PR-Insight)
repo_url: https://github.com/KhulnaSoft/pr-insight
repo_name: KhulnaSoft/pr-insight

nav:
  - Overview:
    - 'index.md'
    - 💎 PR-Insight Pro: 'overview/pr_insight_pro.md'
    - Data Privacy: 'overview/data_privacy.md'
  - Installation:
    - 'installation/index.md'
    - Locally: 'installation/locally.md'
    - GitHub: 'installation/github.md'
    - GitLab: 'installation/gitlab.md'
    - BitBucket: 'installation/bitbucket.md'
    - Azure DevOps: 'installation/azure.md'
    - 💎 PR-Insight Pro: 'installation/pr_insight_pro.md'
  - Usage Guide:
    - 'usage-guide/index.md'
    - Introduction: 'usage-guide/introduction.md'
    - Configuration File: 'usage-guide/configuration_options.md'
    - Usage and Automation: 'usage-guide/automations_and_usage.md'
    - Managing Mail Notifications: 'usage-guide/mail_notifications.md'
    - Changing a Model: 'usage-guide/changing_a_model.md'
    - Additional Configurations: 'usage-guide/additional_configurations.md'
    - 💎 PR-Insight Pro Models: 'usage-guide/PR_insight_pro_models'
  - Tools:
    - 'tools/index.md'
    - Describe: 'tools/describe.md'
    - Review: 'tools/review.md'
    - Improve: 'tools/improve.md'
    - Ask: 'tools/ask.md'
    - Update Changelog: 'tools/update_changelog.md'
    - Similar Issues: 'tools/similar_issues.md'
    - Help Docs: 'tools/help_docs.md'
    - Help: 'tools/help.md'
    - 💎 Analyze: 'tools/analyze.md'
    - 💎 Test: 'tools/test.md'
    - 💎 Improve Component: 'tools/improve_component.md'
    - 💎 Documentation: 'tools/documentation.md'
    - 💎 Custom Labels: 'tools/custom_labels.md'
    - 💎 Custom Prompt: 'tools/custom_prompt.md'
    - 💎 CI Feedback: 'tools/ci_feedback.md'
    - 💎 Similar Code: 'tools/similar_code.md'
  - Core Abilities:
      - 'core-abilities/index.md'
      - Fetching ticket context: 'core-abilities/fetching_ticket_context.md'
      - Local and global metadata: 'core-abilities/metadata.md'
      - Dynamic context: 'core-abilities/dynamic_context.md'
      - Self-reflection: 'core-abilities/self_reflection.md'
      - Impact evaluation: 'core-abilities/impact_evaluation.md'
      - Interactivity: 'core-abilities/interactivity.md'
      - Compression strategy: 'core-abilities/compression_strategy.md'
      - Code-oriented YAML: 'core-abilities/code_oriented_yaml.md'
      - Static code analysis: 'core-abilities/static_code_analysis.md'
      - Code Fine-tuning Benchmark: 'finetuning_benchmark/index.md'
  - Chrome Extension:
      - PR-Insight Chrome Extension: 'chrome-extension/index.md'
      - Features: 'chrome-extension/features.md'
      - Data Privacy: 'chrome-extension/data_privacy.md'
  - FAQ:
      - FAQ: 'faq/index.md'
#  - Code Fine-tuning Benchmark: 'finetuning_benchmark/index.md'

theme:
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
  language: en
  custom_dir: overrides

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: custom
      accent: custom
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: custom
      accent: custom

plugins:
  - social
  - search
  - glightbox

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KhulnaSoft
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/SgSxuQ65GF
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@KhulnaSoft
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/khulnasoft
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/KhulnaSoft
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/khulnasoft/
  analytics:
    provider: custom
    property: ${{ secrets.GOOGLE_ANALYTICS_ID }}

extra_css:
  - css/custom.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - md_in_html
  - attr_list
  - toc:
      title: On this page
      toc_depth: 3
      permalink: true


copyright: |
  &copy; 2024 <a href="https://www.khulnasoft.com/"  target="_blank" rel="noopener">KhulnaSoft</a>
